const SELLER_CREATE_INVOICE = "SELLER_CREATE_INVOICE";
const SELLER_LIST_INVOICE = "SELLER_LIST_INVOICE";
const SELLER_DELETE_INVOICE = "SELLER_DELETE_INVOICE";
const SELLER_LIST_BUYER = "SELLER_LIST_BUYER";

export {
  SELLER_CREATE_INVOICE,
  SELLER_LIST_INVOICE,
  SELLER_DELETE_INVOICE,
  SELLER_LIST_BUYER,
};
