const CREATE_USER = "CREATE_USER";
const LIST_USER = "LIST_USER";
const DELETE_USER = "DELETE_USER";
const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"

export { CREATE_USER, LIST_USER, DELETE_USER, CREATE_USER_FAILURE };